version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production

  admin:
    build:
      context: .
      dockerfile: Dockerfile.admin
    container_name: admin
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      BACKEND_URL: http://backend:4000
    depends_on:
      - backend

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    container_name: consumer
    ports:
      - "3001:3000" # consumer runs on 3000 internally, mapped to 3001
    environment:
      NODE_ENV: production
      BACKEND_URL: http://backend:4000
    depends_on:
      - backend
