FROM node:22-alpine AS base

WORKDIR /app
COPY apps/backend/package*.json ./
RUN npm install
COPY apps/backend ./

FROM base AS development
ENV NODE_ENV=development
EXPOSE 4000
CMD ["npm", "run", "dev"]

FROM base AS production
ENV NODE_ENV=production
RUN npm prune --omit=dev
EXPOSE 4000
CMD ["npm", "start"]
