FROM node:22-alpine AS base

WORKDIR /app
COPY apps/admin/package*.json ./
RUN npm install
COPY apps/admin ./

FROM base AS development
ENV NODE_ENV=development
EXPOSE 3000
CMD ["npm", "run", "dev"]

FROM base AS production
ENV NODE_ENV=production
RUN npm run build
RUN npm prune --omit=dev
EXPOSE 3000
CMD ["npm", "start"]
