version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: party_backend
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: party
    depends_on:
      - db

  admin:
    build:
      context: .
      dockerfile: Dockerfile.admin
    container_name: party_admin
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      BACKEND_URL: http://backend:4000
    depends_on:
      - backend

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    container_name: party_consumer
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: production
      BACKEND_URL: http://backend:4000
    depends_on:
      - backend

  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: party
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: nnandan15@gmail.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgres_data:
